### GET request to example server
POST /api/v1/users/login HTTP/1.1
Host: stayforlong.test:8080
Content-Type: application/json
Content-Length: 61

{
  "email":"jhon.doe@stayforlong.test",
  "password":"doe123"
}