name: CI

on: [push, pull_request]
jobs:
  run-test:
    name: Run testsuite
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-progress --optimize-autoloader --no-scripts"

      - name: Run unit test
        run: vendor/bin/phpunit --testsuite Unit