name: CI

on: [push, pull_request]
jobs:
  run-test:
    name: Run testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6

      - run: echo "Composer dependencies have been installed"

      - uses: php-actions/phpunit@v4
        with:
          php_version: "8.4.5"
          php_extensions: ctype iconv
          configuration: phpunit.xml.dist