name: CI

on: [push, pull_request]
jobs:
  run-test:
    name: Run testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          cp .env.test .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-progress --optimize-autoloader --no-scripts"
          custom-cache-key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Run unit test
        run: vendor/bin/phpunit --testsuite Unit