name: CI

on: [push, pull_request]
jobs:
  setup_php:
    name: Setup PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          cp .env.test .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-progress --optimize-autoloader --no-scripts"
          custom-cache-key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

  run-test:
    name: Run testsuite
    runs-on: ubuntu-latest
    needs: setup_php
    steps:
      - name: Run Unit test
        run: vendor/bin/phpunit --testsuite Unit

      - name: Run Acceptance test
        run: vendor/bin/phpunit --testsuite Acceptance

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: setup_php
    steps:
      - name: Run ECS
        run: vendor/bin/ecs check